FROM python:3.9
WORKDIR /app
COPY streamlit_app.py requirements.txt ./
RUN pip install -r requirements.txt
CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]