apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resume-summary-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/nachikul/ResumeSummariser.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true